#!/usr/bin/python

import sys
from mininet.log import setLogLevel, info
from mn_wifi.cli import CLI
from mn_wifi.net import Mininet_wifi
def topology(args):
	
	net = Mininet_wifi()
	info("*** Creatingnodes\n")
	h1 = net.addHost( 'h1', mac= '00:00:00:00:00:01', ip='10.0.0.1/8' )
	sta1 = net.addStation( 'sta1', mac='00:00:00:00:00:02', ip='10.0.0.2/8', range='20' )
	ap1 = net.addAccessPoint( 'ap1', ssid= 'ap1−ssid', mode= 'g', channel= '1', position='30,50,0', range='30' )
	ap2 = net.addAccessPoint( 'ap2', ssid= 'ap2−ssid', mode= 'g', channel= '1', position='90,50,0', range='30' )
	ap3 = net.addAccessPoint( 'ap3', ssid= 'ap3−ssid', mode= 'g', channel= '1', position='130,50,0',range='30' )
	c1= net.addController( 'c1' )

	info("*** Configuring Propagation Model\n")
	net.setPropagationModel(model="logDistance", exp=4.5)
	
	info("*** Configuringwifinodes\n")
	net.configureWifiNodes()

	info("*** AssociatingandCreatinglinks\n")
	net.addLink(ap1, h1)
	net.addLink(ap1, ap2)
	net.addLink(ap2, ap3)
	
	if '-p' not in args:
		net.plotGraph(max_x=160, max_y=160)
	
	net.startMobility(time=0, AC='ssf')
	net.mobility(sta1, 'start', time=20, position='1,50,0')
	net.mobility(sta1, 'stop', time=79, position='159,50,0')
	net.stopMobility(time=80)

	info("*** Starting network\n")
	net.build()
	c1.start()
	ap1.start( [c1] )
	ap2.start( [c1] )
	ap3.start( [c1] )

	info("*** Running CLI\n")
	CLI( net )

	info("*** Stoppingnetwork\n")
	net.stop()
	
if __name__ == '__main__':
	setLogLevel( 'info' )
	topology(sys.argv)
